{%- set platform = "linux" %}
{%- set application = "Firefox" %}

platform: "{{ platform }}"
appconfig:
  app_name: "{{ application }}"
  app_data_src: "internal"
  internal_state_dir: "/home/{{ container_user }}/.mozilla/firefox"
  running_executable: "firefox"
  use_subprofiles: True
build:
  automatic: True
  dockerfile: "Dockerfile"
  image: "linux/firefox"
  tag: "latest"
  dockerfile_update:
    - USER root
    - apt-get update && apt-get dist-upgrade -y
    - USER sandbox
container:    
  command: ["/usr/bin/firefox", "--no-remote"]
  gpu_hook:
    enabled: True
  image: "linux/firefox"
  tag: "latest"
  shm_size: "1G"
  mounts:
    _full_profile_dir/Downloads: "/home/{{ container_user }}/Downloads"
    _full_profile_dir/cache: "/home/{{ container_user }}/.cache"
devices:
  audio: 
    enabled: False
  hwrender: 
    enabled: True
  joystick: 
    enabled: False
