build_type: "local"
maintenance_dir: "~/.py-docker-x11/maintenance"
appDirs:
  base: "~/.py-docker-x11"
  default: "~/.py-docker-x11/apps"
  driver_cache: "~/.py-docker-x11/driver_cache"
  linux: "~/.py-docker-x11/apps/linux"
  windows: "~/.py-docker-x11/apps/windows"
build:
  always_push: False
  build_dir: "~/.py-docker-x11/builds"
seccomp_dir: "~/.py-docker-x11/seccomp_profiles"
profileDir: "~/.py-docker-x11/profiles"
workDir: "~/.py-docker-x11/work"
container:
  mounts:
    /etc/localtime: "/etc/localtime"
  user: "sandbox"
  user_uid: 1000
  user_gid: 1000
devices:
  joystick:
    enabled: False
  audio:
    enabled: False
  hwrender:
    enabled: False
  network:
    enabled: True
scripts:
  pre_run: "echo \"No pre_run script defined\""
  post_run: "echo \"No post_run script defined\""
  post_exit: "echo \"No post_exit script defined\""
