appDirs:
  base: "~/.py-docker-x11"
  default: "~/.py-docker-x11/apps"
  linux: "~/.py-docker-x11/apps/linux"
  windows: "~/.py-docker-x11/apps/windows"
profileDir: "~/.py-docker-x11/profiles"
workDir: "~/.py-docker-x11/work"
htpc: 
  enabled: False
  binary: "htpc-binary"
docker:
  userSubUID: 297610
  groupSubUID: 297611
container:
  display: ":0.0"
  init: "/usr/bin/dumb-init"
  mounts:
    /etc/localtime: "/etc/localtime"
  user: "sandbox"
devices:
  joystick:
    enabled: False
  audio: 
    enabled: False
    paSocket: "/tmp/pulse-socket"
  hwrender: False
  network: True
scripts:
  pre_run: "echo \"No pre_run script defined\""
  post_run: "echo \"No post_run script defined\""
  post_exit: "echo \"No post_exit script defined\""
